### ISSUE TITLE
statusticker not updating propperly

### ISSUE THREAD

**Issue by ArdjanShero** [hotmeteor/statusticker-support#111]
Hi. I've noticed this before with other services and today with jira and confluence when they had issues. I took a video where you can see that their statuses are not updating. https://shero.d.pr/7yzVVg 
is there a response time for the statuses to show up on statusticker or they should show up immediately?

**Comment by hotmeteor** [comment]
Hey Ardjan. We can only represent what data is available to us, and sometimes the data provided is out of sync with what the services post on their status pages. This is certainly the case with services like Slack and Heroku, and maybe Atlassian.

The alert they posted at `2018-09-26 07:39:56` was captured by us at `2018-09-26 08:20:14` -- over 40 minutes later.

I'll start digging in to see if there's way to get that data sooner, because 40 minutes is way too long for it to really matter.
